### ISSUE TITLE
[错误报告]: win版本无法运行

### ISSUE THREAD

**Issue by ambanmi** [demigody/nas-tools#1]
### 确认

- [X] 我的版本是最新版本，我的版本号与 [version](https://github.com/demigody/nas-tools/releases/latest) 相同。
- [X] 我已经 [issue](https://github.com/demigody/nas-tools/issues) 中搜索过，确认我的问题没有被提出过。
- [X] 我已经修改标题，将标题中的 描述 替换为我遇到的问题。

### 当前程序版本

3.3.16

### 问题类型

主程序运行问题

### 问题描述

win10 运行直接报错 

### 发生问题时系统日志和配置文件

```bash
Traceback (most recent call last):
  File "run.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "web\action.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "cn2an\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "cn2an\cn2an.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "proces\__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "proces\masking.py", line 5, in <module>
  File "proces\util\data.py", line 103, in get_city_pattern
  File "proces\util\data.py", line 10, in get_all_cities
  File "proces\util\conf.py", line 10, in get_yaml
  File "pkg_resources\__init__.py", line 1160, in resource_stream
  File "pkg_resources\__init__.py", line 1409, in get_resource_stream
  File "pkg_resources\__init__.py", line 1412, in get_resource_string
  File "pkg_resources\__init__.py", line 1579, in _get
  File "PyInstaller\loader\pyimod02_importers.py", line 344, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\yyyy\\AppData\\Local\\Temp\\_MEI7762\\proces\\data\\province_city.yaml'
```

**Comment by demigody** [comment]
已修复，最新版本已上传。
